openapi: 3.0.0
info:
  title: API de Tienda de Accesorios de Mascotas
  version: 1.0.0
paths:
  /usuarios:
    get:
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
    post:
      summary: Crear un nuevo usuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuario creado
  /usuarios/{id_user}:
    parameters:
      - name: id_user
        in: path
        required: true
        schema:
          type: integer
    post:
      summary: Crear un nuevo perfil
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Perfil'
      responses:
        '201':
          description: Perfil creado
  /perfiles/{id_perfil}:
    parameters:
      - name: id_perfil
        in: path
        required: true
        schema:
          type: integer

    get:
      summary: Obtener todos los formularios
      responses:
        '200':
          description: Lista de formularios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Formulario'
    post:
      summary: Crear un nuevo formulario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Formulario'
      responses:
        '201':
          description: Formulario creado
  /formularios/{id_form}:
    parameters:
      - name: id_form
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Obtener todos los productos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
    post:
      summary: Crear un nuevo producto
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '201':
          description: Producto creado
  /productos/{id_products}:
    parameters:
      - name: id_products
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Obtener un producto por ID
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '404':
          description: Producto no encontrado
  
    get:
      summary: Obtener todos los pedidos
      responses:
        '200':
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pedido'
    post:
      summary: Crear un nuevo pedido
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pedido'
      responses:
        '201':
          description: Pedido creado
  /pedidos/{pedidoId}:
    parameters:
      - name: pedidoId
        in: path
        required: true
        schema:
          type: integer
    
    get:
      summary: Obtener los detalles de un pedido por ID
      responses:
        '200':
          description: Detalles del pedido encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DetallePedido'
        '404':
          description: Pedido no encontrado
    post:
      summary: Crear un nuevo detalle de pedido
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetallePedido'
      responses:
        '201':
          description: Detalle de pedido creado
components:
  schemas:
    Usuario:
      type: object
      properties:
        Id_user:
          type: integer
        Nombre:
          type: string
        Apellido:
          type: string
        Email:
          type: string
        Contraseña:
          type: string
        Confirm_contraseña:
          type: string
    Perfil:
      type: object
      properties:
        Id_perfil:
          type: integer
        Nombre:
          type: string
        Apellido:
          type: string
        Email:
          type: string
        Contraseña:
          type: string
    Formulario:
      type: object
      properties:
        Id_Form:
          type: integer
        Id_perfil:
          type: integer
        Nombre:
          type: string
        Apellido:
          type: string
        Email:
          type: string
        Image:
          type: string
          format: binary
        Descripción:
          type: string
    Producto:
      type: object
      properties:
        Id_products:
          type: integer
        Nombre:
          type: string
        Precio:
          type: number
          format: float
        Descripción:
          type: string
        Image_url:
          type: string
    Pedido:
      type: object
      properties:
        PedidoID:
          type: integer
        ClienteID:
          type: integer
        FechaPedido:
          type: string
          format: date
        Total:
          type: number
          format: float
    DetallePedido:
      type: object
      properties:
        DetalleID:
          type: integer
        PedidoID:
          type: integer
        ProductoID:
          type: integer
        Cantidad:
          type: integer
        PrecioUnitario:
          type: number
          format: float